#!/usr/bin/env python3
"""
generate_daily_summary.py — Roll up today's session-log entries from all projects
into a single daily note in the global vault.

Scans VAULT/Projects index notes (or a configured projects root) for each project's
.ai-memory/session-log.md, extracts entries dated today, and writes/updates
VAULT/DailyLogs/YYYY-MM-DD.md.

Usage:
    python generate_daily_summary.py --vault ~/AI-Vault --projects-root ~/code
    python generate_daily_summary.py --vault ~/AI-Vault --date 2026-06-10
"""
from __future__ import annotations
import argparse
import datetime as dt
import re
from pathlib import Path


def find_session_logs(projects_root: Path) -> list[Path]:
    """Find all .ai-memory/session-log.md under projects_root (depth-limited)."""
    logs: list[Path] = []
    if not projects_root.exists():
        return logs
    for memdir in projects_root.glob("*/.ai-memory"):
        log = memdir / "session-log.md"
        if log.exists():
            logs.append(log)
    # also one level deeper (e.g. ~/code/org/repo)
    for memdir in projects_root.glob("*/*/.ai-memory"):
        log = memdir / "session-log.md"
        if log.exists():
            logs.append(log)
    return logs


def extract_entries_for_date(log: Path, date_str: str) -> list[str]:
    """Return session entries whose header contains the date."""
    text = log.read_text(encoding="utf-8", errors="ignore")
    # Entries start with '## Session' headers
    blocks = re.split(r"(?=^## Session)", text, flags=re.MULTILINE)
    matched = [b.strip() for b in blocks if date_str in b and b.lstrip().startswith("## Session")]
    return matched


def project_name(log: Path) -> str:
    # .../<project>/.ai-memory/session-log.md
    return log.parent.parent.name


def build_daily_note(date_str: str, sections: dict[str, list[str]]) -> str:
    weekday = dt.date.fromisoformat(date_str).strftime("%A, %B %d, %Y")
    out = [f"---\ntags: [daily, auto-generated]\ntype: daily-note\ndate: {date_str}\n---\n",
           f"# {weekday}\n",
           "> Auto-generated by generate_daily_summary.py\n"]
    if not sections:
        out.append("\n_No session activity recorded today._\n")
    for proj, entries in sorted(sections.items()):
        out.append(f"\n## [[{proj}]] — {len(entries)} session(s)\n")
        for e in entries:
            # indent the entry as a quote for readability
            out.append("\n" + e + "\n")
    out.append(f"\n---\n- Previous: [[{(dt.date.fromisoformat(date_str) - dt.timedelta(days=1)).isoformat()}]]")
    out.append(f"\n- Next: [[{(dt.date.fromisoformat(date_str) + dt.timedelta(days=1)).isoformat()}]]\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True, help="Path to AI-Vault")
    ap.add_argument("--projects-root", help="Where projects live (default: <vault>/../code)")
    ap.add_argument("--date", default=dt.date.today().isoformat())
    args = ap.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    projects_root = Path(args.projects_root).expanduser().resolve() if args.projects_root \
        else vault.parent / "code"

    logs = find_session_logs(projects_root)
    sections: dict[str, list[str]] = {}
    for log in logs:
        entries = extract_entries_for_date(log, args.date)
        if entries:
            sections[project_name(log)] = entries

    daily_dir = vault / "DailyLogs"
    daily_dir.mkdir(parents=True, exist_ok=True)
    out_path = daily_dir / f"{args.date}.md"
    out_path.write_text(build_daily_note(args.date, sections), encoding="utf-8")

    total = sum(len(v) for v in sections.values())
    print(f"Wrote {out_path}")
    print(f"   {len(sections)} project(s), {total} session entr(y/ies) for {args.date}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
