#!/usr/bin/env python3
"""
generate_daily_summary.py — Roll up today's session entries from all projects
into a single daily note in the global vault.

Tier-2 aware: each project keeps one file per session in .ai-memory/sessions/
(filenames are date-prefixed, e.g. 2026-06-18-164530-main.md). This scans each
project's sessions/ for files whose name starts with the target date. For projects
not yet migrated, it falls back to parsing the legacy single .ai-memory/session-log.md.

Usage:
    python generate_daily_summary.py --vault ~/AI-Vault --projects-root ~/code
    python generate_daily_summary.py --vault ~/AI-Vault --date 2026-06-10
"""
from __future__ import annotations
import argparse
import datetime as dt
import re
from pathlib import Path


def find_memdirs(projects_root: Path) -> list[Path]:
    """Find all .ai-memory directories under projects_root (depth-limited)."""
    dirs: list[Path] = []
    if not projects_root.exists():
        return dirs
    for memdir in list(projects_root.glob("*/.ai-memory")) + list(projects_root.glob("*/*/.ai-memory")):
        if memdir.is_dir():
            dirs.append(memdir)
    return dirs


def entries_for_date(memdir: Path, date_str: str) -> list[str]:
    """Session entries for the date. Prefer per-session files; fall back to session-log.md."""
    sessions = memdir / "sessions"
    if sessions.is_dir():
        files = sorted(sessions.glob(f"{date_str}*.md"))
        return [f.read_text(encoding="utf-8", errors="ignore").strip() for f in files]
    # Legacy single-file fallback
    log = memdir / "session-log.md"
    if log.exists():
        text = log.read_text(encoding="utf-8", errors="ignore")
        blocks = re.split(r"(?=^## Session)", text, flags=re.MULTILINE)
        return [b.strip() for b in blocks if date_str in b and b.lstrip().startswith("## Session")]
    return []


def project_name(memdir: Path) -> str:
    # .../<project>/.ai-memory
    return memdir.parent.name


def build_daily_note(date_str: str, sections: dict[str, list[str]]) -> str:
    weekday = dt.date.fromisoformat(date_str).strftime("%A, %B %d, %Y")
    out = [f"---\ntags: [daily, auto-generated]\ntype: daily-note\ndate: {date_str}\n---\n",
           f"# {weekday}\n",
           "> Auto-generated by generate_daily_summary.py\n"]
    if not sections:
        out.append("\n_No session activity recorded today._\n")
    for proj, entries in sorted(sections.items()):
        out.append(f"\n## [[{proj}]] — {len(entries)} session(s)\n")
        for e in entries:
            out.append("\n" + e + "\n")
    out.append(f"\n---\n- Previous: [[{(dt.date.fromisoformat(date_str) - dt.timedelta(days=1)).isoformat()}]]")
    out.append(f"\n- Next: [[{(dt.date.fromisoformat(date_str) + dt.timedelta(days=1)).isoformat()}]]\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True, help="Path to AI-Vault")
    ap.add_argument("--projects-root", help="Where projects live (default: <vault>/../code)")
    ap.add_argument("--date", default=dt.date.today().isoformat())
    args = ap.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    projects_root = Path(args.projects_root).expanduser().resolve() if args.projects_root \
        else vault.parent / "code"

    sections: dict[str, list[str]] = {}
    for memdir in find_memdirs(projects_root):
        entries = entries_for_date(memdir, args.date)
        if entries:
            sections[project_name(memdir)] = entries

    daily_dir = vault / "DailyLogs"
    daily_dir.mkdir(parents=True, exist_ok=True)
    out_path = daily_dir / f"{args.date}.md"
    out_path.write_text(build_daily_note(args.date, sections), encoding="utf-8")

    total = sum(len(v) for v in sections.values())
    print(f"Wrote {out_path}")
    print(f"   {len(sections)} project(s), {total} session entr(y/ies) for {args.date}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
